apiVersion: v1
kind: Service
metadata:
  name: tracker-service
spec:
  type: NodePort
  selector:
    app: tracker-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080